### ISSUE TITLE
BlockingIOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by katprox** [jlmadurga/yowsup-celery#7]
When I call **tasks.connect.delay()** below error happen

>>> from yowsup_celery import tasks
>>> tasks.connect.delay()
<AsyncResult: 5f1546a4-e3d7-4d76-88ca-a6f9ac25c32e>
>>> 

[2020-02-18 20:43:59,731: INFO/MainProcess] Exited state write_e_es_s_ss
[2020-02-18 20:43:59,731: INFO/MainProcess] Entered state read_e_ee_se
I 2020-02-18 20:43:59,731 dissononce.processing.impl.handshakestate - WriteMessage(payload, message_buffer)
[2020-02-18 20:43:59,731: INFO/MainProcess] WriteMessage(payload, message_buffer)
E 2020-02-18 20:44:01,225 yowsup.layers.network.dispatcher.dispatcher_asyncore - Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 47, in handle_read
    data = self.recv(1024)
  File "/usr/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 378, in recv
    return _socket.socket.recv(self._sock, *args)
BlockingIOError: [Errno 11] Resource temporarily unavailable

[2020-02-18 20:44:01,225: ERROR/MainProcess] Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.6/dist-packages/yowsup-3.2.3-py3.6.egg/yowsup/layers/network/dispatcher/dispatcher_asyncore.py", line 47, in handle_read
    data = self.recv(1024)
  File "/usr/lib/python3.6/asyncore.py", line 374, in recv
    data = self.socket.recv(buffer_size)
  File "/usr/local/lib/python3.6/dist-packages/gevent/_socket3.py", line 378, in recv
    return _socket.socket.recv(self._sock, *args)
BlockingIOError: [Errno 11] Resource temporarily unavailable

[2020-02-18 20:44:01,228: INFO/MainProcess] Task yowsup_celery.tasks.connect[22c95acc-5504-4231-9e3a-a01414d1e486] succeeded in 2.0042070349991263s: True
[2020-02-18 20:44:01,230: INFO/MainProcess] Exited state handshake
[2020-02-18 20:44:01,230: INFO/MainProcess] Entered state handshake
I 2020-02-18 20:44:01,231 dissononce.processing.impl.handshakestate - Derived Noise Protocol name Noise_XXfallback_25519_AESGCM_SHA256
[2020-02-18 20:44:01,231: INFO/MainProcess] Derived Noise Protocol name Noise_XXfallback_25519_AESGCM_SHA256
I 2020-02-18 20:44:01,231 dissononce.processing.impl.handshakestate - Processing pre-messages

**Comment by katprox** [comment]
I fixed it with comment out line **33** in **dispatcher_asyncore.py**:

`asyncore.loop(timeout=1)`

This line was blocking the code, preventing other lines to connect to Whatsapp.
